Add missing German translation
rubberduck-vba/Rubberduck pull request #6100
Opened 2023-03-17 16:12 UTC by Rsge

Fixed spelling and wording mistakes and removed leftover commit header fragments of Pull Request #6068 by @INOPIAE.

2023-03-25 20:59 UTC, Vogel612 requested changes

2023-03-25 20:59 UTC, Vogel612 commented on Rubberduck.Resources/Inspections/InspectionInfo.de.resx
> +    <value>Das Kopieren eines Arbeitsblattes, das eine öffentliche Enummerationsdeklartion enthält, wird auch eine Kopie der Enummerationsdeklaration anlegen. Diese Kopie wird einen 'Ambiguous name d
`s/Enummeration/Enumeration/`. Ist so lateinischstämmig, dass sich die Nummer darin noch nicht eingedeutscht hat, daher nur ein "m"

2023-03-25 20:59 UTC, Vogel612 commented on Rubberduck.Resources/Inspections/InspectionInfo.de.resx
> +    <value>Das Kopieren eines Arbeitsblattes, das eine öffentliche Enummerationsdeklartion enthält, wird auch eine Kopie der Enummerationsdeklaration anlegen. Diese Kopie wird einen 'Ambiguous name d
Außerdem: "Die Deklaration~~m~~"

2023-03-25 20:59 UTC, Vogel612 commented on Rubberduck.Resources/Inspections/InspectionInfo.de.resx
> +    <value>MS Forms legt UserForms Steuerelemente als öffentlichen Felder an. Der Zugriff auf diese Felder außerhalb der UserForm-Klasse bricht die Kapselung und verursacht unnötigen Code mit speziel
"öffentliche~~n~~" Felder

Würde `eigene "Modellklassen"` bevorzugen, der zweite Relativsatz braucht noch ein "um".  
Im letzten Satz hat es ein doppeltes Leerzeichen

2023-03-25 20:59 UTC, Vogel612 commented on Rubberduck.Resources/Inspections/InspectionInfo.de.resx
> +    <value>Während eine zustandsbetonte (stateful) Standardinstanz eventuell gewünscht ist, ist diese eine beliebte Quelle von Fehlern und sollte vermieden werden. Nutze die 'Me'-Auszeichnung, um die
Ich kenne statt "zustandsbetont" nur "zustandsbehaftet".

Würde hier außerdem "Während" durch  "Obwohl" ersetzen.

2023-03-25 20:59 UTC, Vogel612 commented on Rubberduck.Resources/Inspections/InspectionInfo.de.resx
> +    <value>Alle Argumente eines Funktions-/Prozedursaufrufes werden immer evaluiert, bevor die Funktion aufgerufen wird, so dass ihre Werte als Parameter übergeben werden. Allerdings führt die 'IIf'-
Prozedur~~s~~aufrufes

2023-03-25 20:59 UTC, Vogel612 commented on Rubberduck.Resources/Inspections/InspectionNames.de.resx
> +    <value>Nur Lesen (Read only) Eigenschaftzuweisung</value>
Statt "Nur Lesen" vielleicht "Schreibgeschützt"?

2023-03-25 20:59 UTC, Vogel612 commented on Rubberduck.Resources/RubberduckUI.de.resx
> +    <value>Vorschaudefinition</value>
Peek definition ist keine Definitionsart, sondern die Anzeige der Definition als Vorschau. Stattdessen also lieber einfach nur "Vorschau". Hilft vermutlich auch beim bearbeiten der "CommandDescription" im nächsten Schlüssel

2023-03-25 21:00 UTC, Vogel612 commented
Please excuse the late review. Nice to see a new face in the German localization area :) I found minor spelling mistakes and have some Formulation suggestions. Looks great otherwise :)

2023-03-26 15:58 UTC, Rsge commented
No problem 🙂 
I already made a small localization contribution a while ago, so I'm not completely new 😉 
I agree with all your corrections, seems I didn't look at @INOPIAE 's changes thoroughly enough, thank you 😅

2023-03-26 16:59 UTC, Vogel612 approved these changes

2023-03-26 17:24 UTC, merged